### ISSUE TITLE
Attention message $make all

### ISSUE THREAD

**Issue by Sharpeye90** [C2Devel/terraform-examples#16]
Хочется предупреждать пользователя о том, что при запуске make all будут запущены все кейсы.

Кейсов очень много, без прерывания операции они будут работать около часа. И случайный запуск make all может вызвать destroy нужных для тестирования объектов.

**Comment by Ubun1** [comment]
В текущей реализации раннера это сделать проблематично. 
Усложнять лишний раз makefile не очень хочется.
