### ISSUE TITLE
Error make show-cases: "column: invalid option -- '-'"

### ISSUE THREAD

**Issue by Sharpeye90** [C2Devel/terraform-examples#6]
**What happened**:
Tried use make show-cases to list all cases, but raised an error: 

`column: invalid option -- '-'
usage: column [-txne] [-c columns] [-s sep] [file ...]
make: *** [Makefile:38: show-cases] Error 1
`

**What you expected to happen**:
List all available cases without errors 

**How to reproduce it (as minimally and precisely as possible)**:
make show-cases statement

**Environment**:
- Terraform v0.11.11
- provider.aws: version = "~> 2.12"
- OS ubuntu 18.10

**Comment by Ubun1** [comment]
pls specify your coreutils version.
