### ISSUE TITLE
aws-provider >= 2.68.0 aws_ami incompatiblity

### ISSUE THREAD

**Issue by Ubun1** [C2Devel/terraform-examples#61]
**What happened**:
https://github.com/terraform-providers/terraform-provider-aws/pull/12038 break our ```aws_ami``` resource because it is necessary to provide custom ```virtualisation_type``` for our api.
this resources is broken:
* aws_ami_launch_permission
* aws_ami
* run_ami_with_tags_filter
* run_instance_with_cdrom
* run_instances_remove_cdrom

**What you expected to happen**:
resource creation

**How to reproduce it (as minimally and precisely as possible)**:

apply aws_ami related resources with aws-provider >= 2.68.0

**Comment by Ubun1** [comment]
addressed in #59

**Comment by Ubun1** [comment]
to be more specific - https://github.com/terraform-providers/terraform-provider-aws/pull/12038/files#diff-333fa51b9bf9981c9825c9c3c9b05d63R219

**Comment by Ubun1** [comment]
@Sharpeye90 глянь этот багос - я кажись в то время прибивал руками версии провайдера, чтоб примеры работали

**Comment by Sharpeye90** [comment]
Теперь все завязано относительно провайдера CROC
