### ISSUE TITLE
Кому нужны эти примеры? 

### ISSUE THREAD

**Issue by John-Beam** [C2Devel/terraform-examples#68]
**What would you like to be added**:
Господа, эти примеры замечательны, но совершенно не подходят под жизненные usecases.  И то что супорт ссылается на это уныние только это уныние множит. 
Сделайте примеры для юзеров, а не для гиков-энтузиастов.

**Why is this needed**:
Да потому что эта куча текста нифига не жизненная.

**Comment by Sharpeye90** [comment]
@John-Beam, эти примеры нужны для базовых действий. Подскажите, какой кейс вы хотели решить?

**Comment by odivlad** [comment]
Закрываем, тк за 2 года нет активности.
