### ISSUE TITLE
Error make all: "call to function 'foreach': missing ')'"

### ISSUE THREAD

**Issue by Sharpeye90** [C2Devel/terraform-examples#7]
**What happened**:
Tried use make all to apply all cases, but raised an error:

`Makefile:25: *** unterminated call to function 'foreach': missing ')'.  Stop.`

**What you expected to happen**:
Executing all cases

**How to reproduce it (as minimally and precisely as possible)**:
`make all `statement

**Environment**:
 - Terraform v0.11.11
 - provider.aws: version = "~> 2.12"
 - OS ubuntu 18.10

**Comment by Ubun1** [comment]
fixed in https://github.com/C2Devel/terraform-examples/pull/11
